### ISSUE TITLE
[Bug] Failed to sign mtl on Ubuntu 2204

### ISSUE THREAD

**Issue by aiChaoSONG** [thesofproject/rimage#107]
The signing process exit with status 234 on Ubuntu22.04, while it is good to sign on ubuntu20.04

The openssl library is upgrade to 3.x on Ubuntu22.04, which I suspect is the root cause.

FATAL ERROR: command exited with status 234: /home/chao/work/sofdev/zsof/build-rimage/rimage -k /home/chao/work/sofdev/zsof/sof/keys/otc_private_key_3k.pem -f 2.0.0 -b 1 -o /home/chao/work/sofdev/zsof/build-mtl/zephyr/zephyr.ri -c /home/chao/work/sofdev/zsof/sof/rimage/config/mtl.toml -i 3 -e /home/chao/work/sofdev/zsof/build-mtl/zephyr/boot.mod /home/chao/work/sofdev/zsof/build-mtl/zephyr/main.mod

**Comment by lgirdwood** [comment]
#109 merged, can we close ?

**Comment by aiChaoSONG** [comment]
close as #109 merged, thanks Jaska
