### ISSUE TITLE
Unable to sign Intel CAVS 

### ISSUE THREAD

**Issue by majunkier** [thesofproject/rimage#147]
**Describe the bug**
For all CAVS platform, when using rimage to sign the binary after last few commits there is an error during signing (not all binary fails): 
```
error: 'alias_mask' not found
error: segment DATA [0xbe018000:0xbe01e000] overlaps with BSS [0xbe01d000:0xbe01e000]
rimage: rimage/src/manifest.c:938: man_write_fw_v1_8: Assertion `image->image_end > MAN_FW_DESC_OFFSET_V1_8' failed.
FATAL ERROR: command exited with status 250: west sign -d <path_config>
```

**Comment by lgirdwood** [comment]
@majunkier the FW DATA section is too big (i.e. not aligned with the SRAM description in the toml file).

**Comment by marc-hb** [comment]
Please re-open with more details if needed
