### ISSUE TITLE
error: ‘ext_length’ may be used uninitialized in this function

### ISSUE THREAD

**Issue by dbaluta** [thesofproject/rimage#164]
We get the following error when compiling `rimage`:

```
/work/x86_64-linux/sof-imx-new/2.5.0-r0/git/rimage/src/adsp_config.c: In function ‘parse_module’:
/work/x86_64-linux/sof-imx-new/2.5.0-r0/git/rimage/src/adsp_config.c:1841:12: error: ‘ext_length’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
|  1841 |  int type, ext_length;

```

This might be a legit warning. 

@paulstelian97  can you please have a look?

**Comment by lgirdwood** [comment]
@paulstelian97 any update ?

**Comment by paulstelian97** [comment]
IIRC there was an internal issue that was forwarded outside, it was a wrong clone.

I'm no longer working with NXP, so this is just from memory.

**Comment by lgirdwood** [comment]
@dbaluta can we close ?

**Comment by dbaluta** [comment]
I don't exactly remembered how we fixed this but it is no longer a problem for IMX yocto builds.
