### ISSUE TITLE
Add CI for rimage

### ISSUE THREAD

**Issue by dbaluta** [thesofproject/rimage#9]
@xiulipan  we need CI for this repo too. At least to check that it compiles.

_Originally posted by @dbaluta in https://github.com/thesofproject/rimage/pull/8#issuecomment-614459106_

CI should minimally do the following:
* compile rimage
* use newly created image to generate SOF binaries

More:
- use qemu to test that SOF binaries can boot correctly

@lgirdwood @xiulipan @jajanusz @akloniex How do we keep sof repo in sync with rimage?

**Comment by xiulipan** [comment]
@dbaluta will enable a simple Travis CI for this repo.

**Comment by finikorg** [comment]
BTW: Do we have ADSP qemu somewhere?

**Comment by lgirdwood** [comment]
@finikorg https://github.com/thesofproject/qemu - Supports BYT -> CAVS25 on Intel side

**Comment by dbaluta** [comment]
> BTW: Do we have ADSP qemu somewhere?

@finikorg what does 'A' from ADSP stands for? I've seen this in qemu and couldn't figure this out. Audio DSP?

**Comment by lgirdwood** [comment]
@dbaluta yep, A == Audio

**Comment by jajanusz** [comment]
> @lgirdwood @xiulipan @jajanusz @akloniex How do we keep sof repo in sync with rimage?

This repo should have no dependency on SOF (even if it has now it has to be fixed). So if SOF depends on rimage than you first update rimage with new features and then use them in SOF.

**Comment by marc-hb** [comment]
Work in progress by @cujomalainey  #49

**Comment by marc-hb** [comment]
Done in:
- #49 
- https://github.com/thesofproject/sof/pull/8328
